site_name: G G G

theme:
  name: material
  features:
    - navigation.indexes

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html

plugins:
  - search:
      lang:
        - en
        - zh

extra:
  analytics:
    provider: google
    property: UA-145083103-1
